export interface Stock {
  id: string;
  symbol: string;
  name: string;
  company_name: string;
  price: number;
  original_price: number;
  market_cap: number;
  original_market_cap: number;
  currency: string;
  usd_rate: number;
  forex_rate: number;
  eps: number;
  book_value_per_share: number;
  price_to_book: number;
  pe_ratio: number;
  pb_ratio: number;
  graham_number: number;
  margin_of_safety: number;
  value_score: number;
  graham_safety_score: number;
  graham_value_score: number;
  is_price_usd: boolean;
  industry: string;
  sector: string;
  exchange: string;
  last_updated: Date;
  current_ratio: number | null;
  long_term_debt_to_equity: number | null;
  net_current_assets: number | null;
  working_capital: number | null;
  earnings_growth_5y: number | null;
  dividend_yield: number | null;
  payout_ratio: number | null;
  roe_5y: number | null;
  roa_5y: number | null;
  revenue_growth_5y: number | null;
  operating_margin: number | null;
  net_profit_margin: number | null;
  safety_score: number;
} 